import { Feature, FeatureCategory } from './types';

// 重新导出 FeatureCategory 类型
export type { FeatureCategory };

/**
 * 功能数据列表
 */
export const featuresData: Feature[] = [
  // 工具类
  {
    id: 'color-picker',
    name: '取色器',
    description: '快速拾取屏幕颜色，支持 HEX/RGB/HSL 格式',
    icon: 'Droplet',
    category: 'tool',
    route: '/feature/color-picker',
    shortcut: 'Ctrl+Alt+C',
    tags: ['颜色', '取色', 'color', 'hex', 'rgb', 'hsl', '拾色器'],
    implemented: true,
  },
  {
    id: 'qr-generator',
    name: '二维码生成器',
    description: '生成自定义二维码，支持多种尺寸和容错级别',
    icon: 'QrCode',
    category: 'tool',
    route: '/feature/qr-generator',
    tags: ['二维码', 'QR', '生成', 'qrcode', 'generator'],
    implemented: true,
  },
  {
    id: 'screenshot',
    name: '截图工具',
    description: '截取屏幕区域，支持延迟截图和标注',
    icon: 'Camera',
    category: 'tool',
    route: '/feature/screenshot',
    shortcut: 'Ctrl+Alt+S',
    tags: ['截图', '屏幕', '捕获', 'screenshot', 'capture', '区域截图'],
    implemented: false,
  },
  {
    id: 'clipboard',
    name: '剪贴板管理',
    description: '管理剪贴板历史记录，支持快速粘贴',
    icon: 'Clipboard',
    category: 'tool',
    route: '/feature/clipboard',
    shortcut: 'Ctrl+Alt+V',
    tags: ['剪贴板', '粘贴', '历史', 'clipboard', 'paste', 'history'],
    implemented: false,
  },
  {
    id: 'screen-ruler',
    name: '屏幕标尺',
    description: '测量屏幕元素尺寸，像素级精度',
    icon: 'Ruler',
    category: 'tool',
    route: '/feature/screen-ruler',
    tags: ['标尺', '测量', '尺寸', 'ruler', 'measure', 'pixel'],
    implemented: false,
  },

  // 系统类
  {
    id: 'search',
    name: '搜索工具',
    description: '文件搜索、网页搜索、应用启动',
    icon: 'Search',
    category: 'system',
    route: '/feature/search',
    tags: ['搜索', '文件', '应用', 'search', 'file', 'launcher'],
    implemented: false,
  },
  {
    id: 'volume-control',
    name: '音量控制',
    description: '快速调整系统音量',
    icon: 'Volume2',
    category: 'system',
    route: '/feature/volume-control',
    tags: ['音量', '声音', 'volume', 'audio', 'sound'],
    implemented: false,
  },
  {
    id: 'brightness-control',
    name: '亮度控制',
    description: '调整屏幕亮度',
    icon: 'Sun',
    category: 'system',
    route: '/feature/brightness-control',
    tags: ['亮度', '屏幕', 'brightness', 'screen'],
    implemented: false,
  },
  {
    id: 'system-info',
    name: '系统信息',
    description: '查看系统硬件和软件信息',
    icon: 'Monitor',
    category: 'system',
    route: '/feature/system-info',
    tags: ['系统', '信息', '硬件', 'system', 'info', 'hardware'],
    implemented: true,
  },

  // 媒体类
  {
    id: 'image-viewer',
    name: '图片查看器',
    description: '快速浏览图片文件',
    icon: 'Image',
    category: 'media',
    route: '/feature/image-viewer',
    tags: ['图片', '查看', 'image', 'viewer', 'photo'],
    implemented: false,
  },
  {
    id: 'audio-recorder',
    name: '录音工具',
    description: '录制音频并保存',
    icon: 'Mic',
    category: 'media',
    route: '/feature/audio-recorder',
    tags: ['录音', '音频', 'record', 'audio', 'microphone'],
    implemented: false,
  },
  {
    id: 'video-converter',
    name: '视频转换',
    description: '转换视频格式',
    icon: 'Video',
    category: 'media',
    route: '/feature/video-converter',
    tags: ['视频', '转换', 'video', 'converter', 'format'],
    implemented: false,
  },

  // 开发类
  {
    id: 'json-formatter',
    name: 'JSON 格式化',
    description: '格式化和验证 JSON 数据',
    icon: 'Braces',
    category: 'dev',
    route: '/feature/json-formatter',
    tags: ['json', '格式化', '验证', 'format', 'validate'],
    implemented: true,
  },
  {
    id: 'html-formatter',
    name: 'HTML 格式化',
    description: '格式化和验证 HTML 代码',
    icon: 'FileCode',
    category: 'dev',
    route: '/feature/html-formatter',
    tags: ['html', '格式化', '验证', 'format', 'validate', '美化'],
    implemented: true,
  },
  {
    id: 'xml-formatter',
    name: 'XML 格式化',
    description: '格式化和验证 XML 数据',
    icon: 'FileText',
    category: 'dev',
    route: '/feature/xml-formatter',
    tags: ['xml', '格式化', '验证', 'format', 'validate', '美化'],
    implemented: true,
  },
  {
    id: 'code-formatter',
    name: '代码格式化',
    description: '支持多种编程语言的代码格式化',
    icon: 'Code',
    category: 'dev',
    route: '/feature/code-formatter',
    tags: ['代码', '格式化', 'java', 'cpp', 'rust', 'python', 'sql', 'javascript', 'typescript'],
    implemented: true,
  },
  {
    id: 'base64-tool',
    name: 'Base64 编解码',
    description: 'Base64 编码和解码工具',
    icon: 'FileCode',
    category: 'dev',
    route: '/feature/base64-tool',
    tags: ['base64', '编码', '解码', 'encode', 'decode'],
    implemented: false,
  },
  {
    id: 'regex-tester',
    name: '正则测试',
    description: '测试和调试正则表达式',
    icon: 'Regex',
    category: 'dev',
    route: '/feature/regex-tester',
    tags: ['正则', 'regex', '表达式', 'regular', 'expression'],
    implemented: false,
  },
  {
    id: 'markdown-preview',
    name: 'Markdown 预览',
    description: '实时预览 Markdown 文档',
    icon: 'FileText',
    category: 'dev',
    route: '/feature/markdown-preview',
    tags: ['markdown', '预览', 'md', 'preview', '文档'],
    implemented: false,
  },
  {
    id: 'color-converter',
    name: '颜色转换',
    description: 'HEX/RGB/HSL 颜色格式转换',
    icon: 'Palette',
    category: 'dev',
    route: '/feature/color-converter',
    tags: ['颜色', '转换', 'hex', 'rgb', 'hsl', 'color', 'convert'],
    implemented: false,
  },
  {
    id: 'timestamp-converter',
    name: '时间戳转换',
    description: 'Unix 时间戳与日期时间转换',
    icon: 'Clock',
    category: 'dev',
    route: '/feature/timestamp-converter',
    tags: ['时间戳', '日期', 'timestamp', 'date', 'time', 'unix'],
    implemented: false,
  },
];

export const implementedFeatures = featuresData.filter((feature) => feature.implemented);

/**
 * 分类信息
 */
export const categories = [
  { id: 'all' as const, name: '全部', icon: 'AppWindow' },
  { id: 'tool' as const, name: '工具', icon: 'Wrench' },
  { id: 'system' as const, name: '系统', icon: 'Settings' },
  { id: 'media' as const, name: '媒体', icon: 'PlayCircle' },
  { id: 'dev' as const, name: '开发', icon: 'Code' },
];
